Traceback (most recent call last):
  File "/home/c/cy123/Sarcasm-Detection/inference_scripts/measure_bert.py", line 300, in <module>
    results = measure_inference_performance(
  File "/home/c/cy123/Sarcasm-Detection/inference_scripts/measure_bert.py", line 118, in measure_inference_performance
    model = AutoModelForSequenceClassification.from_pretrained(model_path)
  File "/home/c/cy123/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/home/c/cy123/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 262, in _wrapper
    return func(*args, **kwargs)
  File "/home/c/cy123/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3808, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/c/cy123/Sarcasm-Detection/inference_scripts/../models/fine_tuned_sbert.
srun: error: xgph2: task 0: Exited with exit code 1
